# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: primary

on:
  workflow_dispatch:
  push:
    branches: [trunk]

jobs:
  primary:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          bump-minor-pre-major: true
          changelog-types: |
            [
              { "type": "feat",      "section": "Features",                  "hidden": false },
              { "type": "fix",       "section": "Bug Fixes",                 "hidden": false },
              { "type": "perf",      "section": "Performance Improvements",  "hidden": false },
              { "type": "revert",    "section": "Reverts",                   "hidden": false },
              { "type": "refactor",  "section": "Code Refactoring",          "hidden": false },
              { "type": "docs",      "section": "Documentation",             "hidden": true },
              { "type": "style",     "section": "Styles",                    "hidden": true },
              { "type": "chore",     "section": "Miscellaneous Chores",      "hidden": true },
              { "type": "test",      "section": "Tests",                     "hidden": true },
              { "type": "build",     "section": "Build System",              "hidden": true },
              { "type": "ci",        "section": "Continuous Integration",    "hidden": true }
            ]
